name: Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rag-project-1
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 256269124934.dkr.ecr.ap-south-1.amazonaws.com
            docker stop k8s-rag-container || true
            docker rm k8s-rag-container || true
            docker pull 256269124934.dkr.ecr.ap-south-1.amazonaws.com/rag-project:latest
            docker run -d \
              --name k8s-rag-container \
              --restart unless-stopped \
              -p 8501:8501 \
              -p 8502:8502 \
              -e LOGFIRE_TOKEN="${{ secrets.LOGFIRE_TOKEN }}" \
              -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
              -e QDRANT_CLUSTER_ENDPOINT="${{ secrets.QDRANT_CLUSTER_ENDPOINT }}" \
              -e QDRANT_API_KEY="${{ secrets.QDRANT_API_KEY }}" \
              -e GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
              -e GROQ_FALLBACK_API_KEY="${{ secrets.GROQ_FALLBACK_API_KEY }}" \
              -e PORTKEY_API_KEY="${{ secrets.PORTKEY_API_KEY }}" \
              -e JUDGE_GROQ="${{ secrets.JUDGE_GROQ }}" \
              -e BACKEND_URL="http://localhost:8080" \
              256269124934.dkr.ecr.ap-south-1.amazonaws.com/rag-project:latest